In [3]:
import numpy as np
import pandas as pd
from numpy import *

In [4]:
#Câu 1:

data = np.loadtxt("bostonh.dat")
print(data)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 3.9690e+02 4.9800e+00 2.4000e+01]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 3.9690e+02 9.1400e+00 2.1600e+01]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 3.9283e+02 4.0300e+00 3.4700e+01]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 5.6400e+00 2.3900e+01]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 3.9345e+02 6.4800e+00 2.2000e+01]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 7.8800e+00 1.1900e+01]]


In [5]:
#Câu 2:

X =np.append(np.ones((len(data),1)),data[:,:13],axis =1)
print(X)
print("-----")
Y = data.transpose()[-1].reshape(len(data),1)
print(Y)

[[1.0000e+00 6.3200e-03 1.8000e+01 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [1.0000e+00 2.7310e-02 0.0000e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [1.0000e+00 2.7290e-02 0.0000e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [1.0000e+00 6.0760e-02 0.0000e+00 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0000e+00 1.0959e-01 0.0000e+00 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [1.0000e+00 4.7410e-02 0.0000e+00 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
-----
[[24. ]
 [21.6]
 [34.7]
 [33.4]
 [36.2]
 [28.7]
 [22.9]
 [27.1]
 [16.5]
 [18.9]
 [15. ]
 [18.9]
 [21.7]
 [20.4]
 [18.2]
 [19.9]
 [23.1]
 [17.5]
 [20.2]
 [18.2]
 [13.6]
 [19.6]
 [15.2]
 [14.5]
 [15.6]
 [13.9]
 [16.6]
 [14.8]
 [18.4]
 [21. ]
 [12.7]
 [14.5]
 [13.2]
 [13.1]
 [13.5]
 [18.9]
 [20. ]
 [21. ]
 [24.7]
 [30.8]
 [34.9]
 [26.6]
 [25.3]
 [24.7]
 [21.2]
 [19.3]
 [20. ]
 [16.6]
 [14.4]
 [19.4]
 [19.7]
 [20.5]
 [25. ]
 [23.4]
 [18.9]
 [35.4]
 [24.7]
 [31.6]
 [23.3]
 [19.6]
 [18.7]
 [16. ]
 [22.2]
 [25. ]
 [33. ]
 [23.5]
 [19.4]
 [22. ]
 [17.4

In [6]:
#Câu 3:

x_T = X.transpose()
print(x_T)
#Tính vecto B
beta = linalg.inv(x_T.dot(X)).dot(x_T).dot(Y)
print(beta)

[[1.0000e+00 1.0000e+00 1.0000e+00 ... 1.0000e+00 1.0000e+00 1.0000e+00]
 [6.3200e-03 2.7310e-02 2.7290e-02 ... 6.0760e-02 1.0959e-01 4.7410e-02]
 [1.8000e+01 0.0000e+00 0.0000e+00 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 ...
 [1.5300e+01 1.7800e+01 1.7800e+01 ... 2.1000e+01 2.1000e+01 2.1000e+01]
 [3.9690e+02 3.9690e+02 3.9283e+02 ... 3.9690e+02 3.9345e+02 3.9690e+02]
 [4.9800e+00 9.1400e+00 4.0300e+00 ... 5.6400e+00 6.4800e+00 7.8800e+00]]
[[ 3.64594884e+01]
 [-1.08011358e-01]
 [ 4.64204584e-02]
 [ 2.05586264e-02]
 [ 2.68673382e+00]
 [-1.77666112e+01]
 [ 3.80986521e+00]
 [ 6.92224640e-04]
 [-1.47556685e+00]
 [ 3.06049479e-01]
 [-1.23345939e-02]
 [-9.52747232e-01]
 [ 9.31168327e-03]
 [-5.24758378e-01]]


In [7]:
#Câu 4:
#Tính C:

C = linalg.inv(x_T.dot(X))
print(C)

[[ 1.15665067e+00 -4.79507297e-04 -7.27912374e-05  7.81007312e-04
  -5.30636011e-03 -4.72633728e-01 -6.72009691e-02  2.52574657e-04
  -1.60858766e-02  4.27955175e-03 -9.32179147e-05 -1.77832398e-02
  -1.77463251e-04 -3.44062107e-03]
 [-4.79507297e-04  4.79667291e-05 -1.74622146e-06  3.33058300e-06
   6.29163676e-05  3.32353579e-04  1.60589501e-05 -6.44104667e-08
   3.40052584e-05 -2.58500572e-05  6.50408184e-08  3.99960618e-06
   4.60269987e-07 -1.13029256e-05]
 [-7.27912374e-05 -1.74622146e-06  8.36861245e-06  3.98676259e-06
  -7.75453928e-06  8.33368670e-05 -3.96939822e-05  9.71684642e-07
  -4.89624081e-05  4.27993705e-06 -5.11685476e-07  2.48176992e-05
  -1.86831132e-08 -1.64268535e-06]
 [ 7.81007312e-04  3.33058300e-06  3.98676259e-06  1.67943163e-04
  -2.42364262e-04 -2.75364026e-03  1.04925166e-04 -3.97527513e-08
   1.14987074e-04  5.04398943e-05 -4.49769287e-06 -4.64149258e-05
   2.43976935e-07 -1.05525682e-05]
 [-5.30636011e-03  6.29163676e-05 -7.75453928e-06 -2.42364262e-04
  

In [8]:
#Tính y mũ:

y_mu = X.dot(beta)
print(y_mu)

[[30.00384338]
 [25.02556238]
 [30.56759672]
 [28.60703649]
 [27.94352423]
 [25.25628446]
 [23.00180827]
 [19.53598843]
 [11.52363685]
 [18.92026211]
 [18.99949651]
 [21.58679568]
 [20.90652153]
 [19.55290281]
 [19.28348205]
 [19.29748321]
 [20.52750979]
 [16.91140135]
 [16.17801106]
 [18.40613603]
 [12.52385753]
 [17.67103669]
 [15.83288129]
 [13.80628535]
 [15.67833832]
 [13.38668561]
 [15.46397655]
 [14.70847428]
 [19.54737285]
 [20.8764282 ]
 [11.45511759]
 [18.05923295]
 [ 8.81105736]
 [14.28275814]
 [13.70675891]
 [23.81463526]
 [22.34193708]
 [23.10891142]
 [22.91502612]
 [31.35762569]
 [34.21510225]
 [28.02056414]
 [25.20386628]
 [24.60979273]
 [22.94149176]
 [22.09669817]
 [20.42320032]
 [18.03655088]
 [ 9.10655377]
 [17.20607751]
 [21.28152535]
 [23.97222285]
 [27.6558508 ]
 [24.04901809]
 [15.3618477 ]
 [31.15264947]
 [24.85686978]
 [33.10919806]
 [21.77537987]
 [21.08493555]
 [17.8725804 ]
 [18.51110208]
 [23.98742856]
 [22.55408869]
 [23.37308644]
 [30.36148358]
 [25.53056

In [9]:
#Tính e mũ:

e = Y - y_mu
print(e)

[[-6.00384338e+00]
 [-3.42556238e+00]
 [ 4.13240328e+00]
 [ 4.79296351e+00]
 [ 8.25647577e+00]
 [ 3.44371554e+00]
 [-1.01808268e-01]
 [ 7.56401157e+00]
 [ 4.97636315e+00]
 [-2.02621071e-02]
 [-3.99949651e+00]
 [-2.68679568e+00]
 [ 7.93478472e-01]
 [ 8.47097189e-01]
 [-1.08348205e+00]
 [ 6.02516792e-01]
 [ 2.57249021e+00]
 [ 5.88598653e-01]
 [ 4.02198894e+00]
 [-2.06136033e-01]
 [ 1.07614247e+00]
 [ 1.92896331e+00]
 [-6.32881292e-01]
 [ 6.93714654e-01]
 [-7.83383155e-02]
 [ 5.13314391e-01]
 [ 1.13602345e+00]
 [ 9.15257194e-02]
 [-1.14737285e+00]
 [ 1.23571798e-01]
 [ 1.24488241e+00]
 [-3.55923295e+00]
 [ 4.38894264e+00]
 [-1.18275814e+00]
 [-2.06758913e-01]
 [-4.91463526e+00]
 [-2.34193708e+00]
 [-2.10891142e+00]
 [ 1.78497388e+00]
 [-5.57625688e-01]
 [ 6.84897746e-01]
 [-1.42056414e+00]
 [ 9.61337195e-02]
 [ 9.02072746e-02]
 [-1.74149176e+00]
 [-2.79669817e+00]
 [-4.23200323e-01]
 [-1.43655088e+00]
 [ 5.29344623e+00]
 [ 2.19392249e+00]
 [-1.58152535e+00]
 [-3.47222285e+00]
 [-2.6558508

In [10]:
#Tính sigma bình:
sigma = (transpose(e).dot(e)) / (len(X) - (13+1))
print(sigma)

[[22.51785483]]


In [11]:
#Tính SE_beta:

SE_beta = sigma*np.diag(C)
print(SE_beta)

[[2.60452918e+01 1.08010784e-03 1.88443200e-04 3.78171976e-03
  7.42319676e-01 1.45904420e+01 1.74661518e-01 1.74498340e-04
  3.97821912e-02 4.40185014e-03 1.41416344e-05 1.71156401e-02
  7.21440767e-06 2.57203944e-03]]


In [12]:
#Câu 5: Xây dựng KTC cho beta:

import scipy.stats as scipy
t = (1 - 0.99)/2
t_value = scipy.t.ppf(t,len(X) - (13+1))
VT = beta - t_value * SE_beta
VP = beta + t_value * SE_beta
print(VT,VP)

[[ 1.03808938e+02  3.64622814e+01  3.64599757e+01  3.64692674e+01
   3.83790223e+01  7.41883125e+01  3.69111384e+01  3.64599396e+01
   3.65623595e+01  3.64708709e+01  3.64595250e+01  3.65037470e+01
   3.64595070e+01  3.64661393e+01]
 [ 6.72414380e+01 -1.05218351e-01 -1.07524070e-01 -9.82323642e-02
   1.81152257e+00  3.76208127e+01  3.43638680e-01 -1.07560130e-01
  -5.14022526e-03 -9.66287945e-02 -1.07974790e-01 -6.37527279e-02
  -1.07992702e-01 -1.01360427e-01]
 [ 6.73958698e+01  4.92134648e-02  4.69077459e-02  5.61994520e-02
   1.96595439e+00  3.77752445e+01  4.98070496e-01  4.68716865e-02
   1.49291591e-01  5.78030217e-02  4.64570266e-02  9.06790883e-02
   4.64391138e-02  5.30713894e-02]
 [ 6.73700080e+01  2.33516328e-02  2.10459139e-02  3.03376200e-02
   1.94009256e+00  3.77493827e+01  4.72208664e-01  2.10098545e-02
   1.23429759e-01  3.19411897e-02  2.05951946e-02  6.48172563e-02
   2.05772818e-02  2.72095574e-02]
 [ 7.00361831e+01  2.68952683e+00  2.68722111e+00  2.69651281e+00
  

In [13]:
#Câu 6:

#Tính y mũ của câu 6: với x mũ là hàm tự cho
t = (1 - 0.95)/2
t_value = scipy.t.ppf(t,len(X) - (13+1))
data1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
x_mu_nho = np.array(data1)
y_mu_moi = x_mu_nho.dot(beta)
print(y_mu_moi)

[-59.04026202]


In [14]:
#Tính epsilon:
import math

canbachai = sigma*(1+transpose(x_mu_nho).dot(C).dot(x_mu_nho))
epsilon = abs(t_value*canbachai)
print(epsilon)

VT1 = float(y_mu_moi - epsilon)
VP1 = float(y_mu_moi + epsilon)
print("Khoảng tin cậy của y là:")
(VT1,VP1)

[[957.24609699]]
Khoảng tin cậy của y là:


(-1016.2863590120626, 898.2058349725091)

In [15]:
#Câu 7

#Tính SSR:
sum_y = 0
for i in Y:
    sum_y = sum_y + i
print("Sum của y là: ",sum_y)
    
SSR = transpose(beta).dot(transpose(X)).dot(Y) - (1/len(Y))*((sum_y)**2)
print("SSR là : ",SSR)

#Tính SST:
SST = transpose(Y).dot(Y) - (1/len(Y))*((sum_y)**2)
print("SST là: ",SST)

#Tính SSE:
SSE = SST - SSR
print("SSE là: ",SSE)


Sum của y là:  [11401.6]
SSR là :  [[31637.51083705]]
SST là:  [[42716.29541502]]
SSE là:  [[11078.78457797]]


In [16]:
#Lập bảng Anova:
#Tính trung bình bình phương MSR và MSE:
MSR = (SSR/13)
print("MSR là: ",MSR)

MSE = (SSE/(len(X)-(13+1)))
print("MSE là: ",MSR)

#Tính F0:
F0 = MSR/MSE
print("F0 là: ",F0)

#Cách lập bảng ANOVA:

import pandas as pd
s = {'Tên đại lượng': pd.Series(['Hồi quy bội','Sai số (hay thặng dư)','Tổng']),
    'Tổng bình phương': pd.Series([SSR,SSE,SST]),
    'Bậc tự do': pd.Series([13,len(X)-(13+1),len(X)]),
    'Trung bình bình phương': pd.Series([MSR,MSE,' ']),
    'F0': pd.Series([F0,' ',' '])}

df = pd.DataFrame(s)
print(df)

MSR là:  [[2433.65467977]]
MSE là:  [[2433.65467977]]
F0 là:  [[108.07666617]]
           Tên đại lượng        Tổng bình phương  Bậc tự do  \
0            Hồi quy bội  [[31637.510837046662]]         13   
1  Sai số (hay thặng dư)  [[11078.784577972605]]        492   
2                   Tổng   [[42716.29541501927]]        506   

   Trung bình bình phương                      F0  
0    [[2433.65467977282]]  [[108.07666617409232]]  
1  [[22.517854833277653]]                          
2                                                  


In [24]:
#Tính F-Test:
alpha = 0.95
t_value = 1-(alpha/2)
f = scipy.f.ppf(t_value, 13, len(X)-(13+1))
print("F-Test là: ",f)


F-Test là:  0.974901300750161


In [25]:
#Câu 8:
import scipy.stats as scipy



def kd_tung_heso_cua_mohinh(X,Y,j,alpha,bj_0):
    beta = np.linalg.inv(transpose(X).dot(X)).dot(transpose(X)).dot(Y)
    C = linalg.inv(transpose(X).dot(X))
    y_mu = X.dot(beta)
    e = Y - y_mu
    SE_beta = sigma*np.diag(C)
    t = (alpha)/2
    tu_do = len(X)-(13+1)
    t_value = abs(scipy.t.ppf(t,tu_do))
    print(t_value)
    KTC_trai = beta[j] - t_value*transpose(SE_beta)[j]
    KTC_phai= beta[j]+ t_value*transpose(SE_beta)[j]
    print("Khoang tin cay cho Bj la: ")
    print(KTC_trai,",", KTC_phai)
    T0 = ((beta[j] - bj_0)/transpose(SE_beta)[j])
    if T0 > t_value:
        print("Bac bo H0")
    else:
        print("Chua du co so bac bo H0")
    
kd_tung_heso_cua_mohinh(X,Y,12,0.05,0)

1.9647973556539153
Khoang tin cay cho Bj la: 
[0.00929751] , [0.00932586]
Bac bo H0
