#Họ tên: Trịnh Ngọc Hiến
#MSSV: 19110315
#Bài Thực hành Lab01

In [26]:
import pandas as pd
df = pd.read_csv("House_Price_2.csv") 
df.head()

width  length         price
0     28      97  3.350184e+08
1     21      62  2.298295e+08
2     27      64  2.603552e+08
3      5      92  2.064708e+08
4     13      84  2.339808e+08

In [27]:
x1 = df['width'].values  
print(x1.shape)  ## trích width thành một mảng numpy
x1 = x1.reshape(-1, 1)                     ## chuyển thành ma trận cột
print(x1.shape)

(100,)
(100, 1)


In [28]:
x2 = df['length'].values   ## Trích length 
print(x2.shape)
x2 = x2.reshape(-1,1)
print(x2.shape)

(100,)
(100, 1)


In [29]:
y = df['price'].values   ## Trích giá tiền 
print(y.shape)
y = y.reshape(-1,1)
print(y.shape)

(100,)
(100, 1)


In [30]:
import numpy as np
Z = np.concatenate([x1,x2, np.ones((100,1))], axis=-1)   ## thêm một cột vào sau X và gán vào Z
Z = Z.astype(np.float32)                                 ## chuyển sang float
print(Z)

[[28. 97.  1.]
 [21. 62.  1.]
 [27. 64.  1.]
 [ 5. 92.  1.]
 [13. 84.  1.]
 [ 6. 62.  1.]
 [14. 60.  1.]
 [22. 72.  1.]
 [29. 84.  1.]
 [29. 60.  1.]
 [18. 37.  1.]
 [20. 32.  1.]
 [15. 96.  1.]
 [23. 58.  1.]
 [29. 86.  1.]
 [26. 50.  1.]
 [25. 83.  1.]
 [ 7. 73.  1.]
 [24. 92.  1.]
 [23. 65.  1.]
 [14. 79.  1.]
 [23. 33.  1.]
 [15. 47.  1.]
 [ 8. 46.  1.]
 [23. 88.  1.]
 [16. 61.  1.]
 [25. 94.  1.]
 [24. 56.  1.]
 [12. 48.  1.]
 [14. 71.  1.]
 [13. 60.  1.]
 [11. 30.  1.]
 [10. 25.  1.]
 [28. 84.  1.]
 [28. 63.  1.]
 [20. 26.  1.]
 [ 5. 24.  1.]
 [26. 91.  1.]
 [20. 39.  1.]
 [23. 38.  1.]
 [18. 41.  1.]
 [20. 81.  1.]
 [20. 75.  1.]
 [10. 39.  1.]
 [25. 45.  1.]
 [ 9. 25.  1.]
 [ 9. 40.  1.]
 [15. 83.  1.]
 [25. 23.  1.]
 [ 8. 31.  1.]
 [13. 40.  1.]
 [27. 80.  1.]
 [ 7. 93.  1.]
 [28. 30.  1.]
 [16. 56.  1.]
 [12. 68.  1.]
 [ 9. 63.  1.]
 [ 8. 58.  1.]
 [22. 27.  1.]
 [22. 88.  1.]
 [12. 48.  1.]
 [ 7. 48.  1.]
 [ 5. 55.  1.]
 [ 8. 72.  1.]
 [11. 39.  1.]
 [16. 78.  1.]
 [22. 25. 

In [31]:
#Từ đó ta tính y = (a1x1 + a2x2) + b
#Giá trị a1, a2  và b tìm được
a_1, a_2, b = np.matmul(np.matmul(np.linalg.inv(np.matmul(Z.T,Z)), Z.T), y)
print(a_1, a_2, b)


[4992436.84085821] [1997577.18059168] [844955.43460693]


In [32]:
#Trường hợp width = 5 length = 10

w_1 = 5
l_1 = 10
price_1 = (a_1 * w_1 + a_2 * l_1) + b
print("Với width = 5 và length = 10 thì có giá là: ")
print(price_1)

Với width = 5 và length = 10 thì có giá là: 
[45782911.44481482]


In [33]:
#Trường hợp width = 20, length = 20

w_2 = 20 
l_2 = 20
price_2 = (a_1 * w_2 + a_2 * l_2) + b
print("Với width = 20 và length = 20 thì có giá là: ")
print(price_2)

Với width = 20 và length = 20 thì có giá là: 
[1.40645236e+08]


In [34]:
#Trường hợp width = 10, length = 40

w_3 = 10
l_3 = 40
price_3 = (a_1 * w_3 + a_2 * l_3) + b
print("Với width = 10 và length = 40 thì có giá là: ")
print(price_3)

Với width = 10 và length = 40 thì có giá là: 
[1.30672411e+08]
