In [ ]:
import numpy as np
import pandas as pd

In [ ]:
def truyxuat_file(i):
  t = open ( str(i)+'.txt' , 'r')
  l = []
  h = []
  l = [ line.split() for line in t]
  x = np.array(l)
  for i in x:
    h.append(i.astype(float))
  h = np.array(h)
  return h

In [ ]:
t = range(1,980)
sum_file=[]
for i in t:
  sum_file.append(truyxuat_file(i))

In [ ]:
print(sum_file[978])

[[41. 33. 52.]
 [39. 31. 52.]
 [39. 34. 52.]
 ...
 [39. 37. 51.]
 [39. 37. 53.]
 [39. 35. 51.]]


In [ ]:
sum_file = np.array(sum_file)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


In [ ]:
sum_shape = []
for i in sum_file:
  sum_shape.append(i.shape[0])

In [ ]:
print(np.max(sum_shape))

9318


In [ ]:
print(truyxuat_file(1))

[[22. 49. 35.]
 [22. 49. 35.]
 [22. 52. 35.]
 ...
 [23. 42. 44.]
 [22. 40. 43.]
 [20. 44. 46.]]


In [ ]:
columns = ['x','y','z']
h = []
for i in sum_file:
  h.append(pd.DataFrame(data = i, columns = columns))


In [ ]:
h=np.array(h)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


In [ ]:
t = []
column= ['x','y','z']
for i in range(0,len(h)):
  for j in column:
    t.append(h[i][j])

In [ ]:
def fourierExtrapolation(x, n_predict):
    n = x.size
    n_harm = 10                     # number of harmonics in model
    t = np.arange(0, n)
    p = np.polyfit(t, x, 1)         # find linear trend in x
    x_notrend = x - p[0] * t        # detrended x
    x_freqdom = fft.fft(x_notrend)  # detrended x in frequency domain
    f = fft.fftfreq(n)              # frequencies
    indexes = list(range(n))
    # sort indexes by frequency, lower -> higher
    indexes.sort(key = lambda i: np.absolute(f[i]))
 
    t = np.arange(0, n + n_predict)
    restored_sig = np.zeros(t.size)
    for i in indexes[:1 + n_harm * 2]:
        ampli = np.absolute(x_freqdom[i]) / n   # amplitude
        phase = np.angle(x_freqdom[i])          # phase
        restored_sig += ampli * np.cos(2 * np.pi * f[i] * t + phase)
    return restored_sig + p[0] * t

In [ ]:
sub_shape = []
for i in sum_shape:
  sub_shape.append(abs(9320-i))

In [ ]:
sum = []
for i in range(0,6):
  print(t[i].shape)


(2167,)
(2167,)
(2167,)
(844,)
(844,)
(844,)


In [ ]:
print(sub_shape)

[7153, 8476, 7092, 7157, 6121, 6543, 6299, 6848, 6823, 6355, 6170, 6974, 9070, 9070, 9070, 9070, 9070, 9070, 9070, 9070, 9070, 9070, 9070, 9070, 9070, 9070, 9070, 9070, 9070, 9070, 9070, 9070, 9050, 9050, 9050, 9050, 9050, 9050, 9125, 8781, 8873, 8828, 8897, 8915, 8889, 8901, 8857, 8969, 8964, 8878, 8862, 9050, 8887, 8790, 8863, 8906, 8861, 8893, 8889, 8885, 8950, 8872, 8985, 8889, 9027, 8880, 9019, 9154, 9104, 8938, 8942, 8978, 8765, 8812, 8515, 8796, 8877, 8855, 8802, 8834, 8913, 8919, 8840, 8908, 8865, 8903, 8914, 8926, 8903, 8942, 8935, 8934, 8959, 8904, 8943, 8920, 8940, 8892, 8920, 8916, 8882, 8866, 8856, 8940, 8954, 8901, 8932, 8935, 9018, 8867, 8956, 8895, 8963, 8847, 8912, 9014, 9037, 8925, 9040, 9033, 9067, 8940, 9065, 8974, 9047, 8952, 8961, 8842, 8936, 8869, 8943, 8864, 8928, 8868, 8487, 8583, 8502, 8038, 8398, 8553, 8381, 8578, 8683, 8310, 8601, 8507, 8480, 8436, 8487, 8643, 8684, 8543, 8508, 8645, 8917, 8677, 8736, 8749, 8733, 8586, 8638, 8514, 8567, 8509, 8743, 8726, 878

In [ ]:
print(t[2].shape)

(2167,)


#Flatten

In [ ]:
import numpy as np

In [ ]:
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7,8,9], [10, 11, 12]]])
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
b.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
b.flatten(order = "F")

array([ 1,  7,  4, 10,  2,  8,  5, 11,  3,  9,  6, 12])

In [ ]:
b.flatten(order = 'K')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
b.flatten(order = 'A')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
for i in range(0, len(sub_shape)):
  for j in range(0, len(temp)):
    if j % 3 != 0 or j == 0:
      print(i,j)
    if j > 0 and j % 3 == 0:
      i = i + 1
      print("\n")
      print(i,j)
      if i > len(sub_shape):
        break
  break