# HIGH DIMENSIONAL ANALYSIS
# Programing Exercise: 02
# Name: Trịnh Ngọc Hiến
# Student code: 19110315

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import matplotlib.gridspec as gridspec

In [2]:
data = sns.load_dataset('iris')
display(data.head())
print(data.shape)


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

(150, 5)


# LDA (Linear Discriminant Analysis)


1) Tính ma trận phân tán bên trong lớp:

$S_W = \sum_{c} S_c$

$S_c = \sum_{i\in{c}}(x_i - \overline{x}_c) \,\,.\,(\overline{x}_c - \overline{x})^T$

2) Tính khoảng giữa ma trận phân tán lớp:

$S_B = \sum_{c} n_c \, . \, (\overline{x}_c - \overline{x}) \, . \, (\overline{x}_c - \overline{x})^T$





In [3]:
x = data.iloc[:,:4].values


In [4]:
y = []
for i in data['species']:
  if i =='setosa':
    y.append(0)
  if i == 'versicolor':
    y.append(1)
  if i == 'virginica':
    y.append(2)

y = np.array(y)
labels = np.unique(y)

In [5]:
n_features = x.shape[1]
n_features

4

In [6]:
mean_overall = np.mean(x, axis=0)
mean_overall

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

### Khởi tạo $S_W$ và $S_B$ và tiến hành tính:

In [7]:
S_W = np.zeros((n_features, n_features))
S_B = np.zeros((n_features, n_features))


for c in labels:
  x_c = x[y==c]
  mean_c = np.mean(x_c, axis=0)
  S_W += (x_c - mean_c).T.dot(x_c - mean_c)

  n_c = x_c.shape[0]
  mean_diff = (mean_c - mean_overall).reshape(n_features, 1)
  S_B += n_c * (mean_diff).dot(mean_diff.T)




### Tính trị riêng và vector riêng sau đó sắp xếp theo thứ tự:

Với Trị riêng và Vector riêng được tính theo $S_W^{-1} S_B$

In [8]:
A = np.linalg.inv(S_W).dot(S_B)
eigenvalues, eigenvectors = np.linalg.eig(A)
eigenvectors = eigenvectors.T
#Sắp xếp vecto riêng và giá trị riêng theo thứ tự từ bé đến lớn
idxs = np.argsort(abs(eigenvalues))[::-1]
eigenvalues = eigenvalues[idxs]
eigenvectors = eigenvectors[idxs]
print("Eigenvalues: ",eigenvalues,"\n","\n","Eigenvectors: ",eigenvectors)

Eigenvalues:  [3.21919292e+01+0.0000000e+00j 2.85391043e-01+0.0000000e+00j
 2.57416716e-15-2.0216843e-15j 2.57416716e-15+2.0216843e-15j] 
 
 Eigenvectors:  [[ 0.20874182+0.j          0.38620369+0.j         -0.55401172+0.j
  -0.7073504 +0.j        ]
 [-0.00653196+0.j         -0.58661055+0.j          0.25256154+0.j
  -0.76945309+0.j        ]
 [ 0.74081322-0.j         -0.37975771+0.12422603j -0.38918222+0.15018108j
   0.13897682-0.31339437j]
 [ 0.74081322+0.j         -0.37975771-0.12422603j -0.38918222-0.15018108j
   0.13897682+0.31339437j]]


In [9]:
explained_variances = []
for i in range(len(eigenvalues)):
    explained_variances.append(eigenvalues[i] / np.sum(eigenvalues))
 
print("Sum of Explained Variances: ",np.sum(explained_variances), '\nExplained Variances:', explained_variances)

Sum of Explained Variances:  (0.9999999999999999+0j) 
Explained Variances: [(0.9912126049653671+0j), (0.008787395034632713+0j), (7.926045436407321e-17-6.224911075752114e-17j), (7.926045436407321e-17+6.224911075752114e-17j)]


In [10]:
print("Vecto riêng ứng với PC1", eigenvectors[:,0])
print("Vecto riêng ứng với PC2", eigenvectors[:,1])

Vecto riêng ứng với PC1 [ 0.20874182+0.j -0.00653196+0.j  0.74081322-0.j  0.74081322+0.j]
Vecto riêng ứng với PC2 [ 0.38620369+0.j         -0.58661055+0.j         -0.37975771+0.12422603j
 -0.37975771-0.12422603j]


# PCA (Principal Components Analysis)


In [11]:
X = data.iloc[:,:4].values


In [12]:
def pca_alg(data):

  #tính vector trung bình dữ liệu
  
  kyvong = np.mean(data,axis = 0)

  #Trừ mỗi điểm dữ liệu cho vector trung bình
  X_std = (data - kyvong)/np.std(data,axis = 0)

  #Tính ma trận hiệp phương sai
  features = X_std.T
  cov_matrix = np.cov(features)

  #Tính các cặp trị riêng, vector riêng và sắp xếp theo thứ tự giảm dần tri riêng
  values, vectors = np.linalg.eig(cov_matrix)
  eig_values = values[np.argsort(values)[::-1]]
  eig_vectors = vectors[:,np.argsort(values)[::-1]]

  return eig_values, eig_vectors

In [13]:
eig_values, eig_vectors = pca_alg(X)
print("Eig_values: ",eig_values)
print("Eig_vectors: ",eig_vectors)

Eig_values:  [2.93808505 0.9201649  0.14774182 0.02085386]
Eig_vectors:  [[ 0.52106591 -0.37741762 -0.71956635  0.26128628]
 [-0.26934744 -0.92329566  0.24438178 -0.12350962]
 [ 0.5804131  -0.02449161  0.14212637 -0.80144925]
 [ 0.56485654 -0.06694199  0.63427274  0.52359713]]


In [14]:
explained_variances = []
for i in range(len(eig_values)):
    explained_variances.append(eig_values[i] / np.sum(eig_values))
 
print("Sum of Explained Variances: ",np.sum(explained_variances), '\nExplained Variances:', explained_variances)

Sum of Explained Variances:  0.9999999999999999 
Explained Variances: [0.729624454132999, 0.22850761786701723, 0.03668921889282867, 0.005178709107155017]


In [15]:
print("Vecto riêng ứng với PC1", eig_vectors[:,0])
print("Vecto riêng ứng với PC2", eig_vectors[:,1])

Vecto riêng ứng với PC1 [ 0.52106591 -0.26934744  0.5804131   0.56485654]
Vecto riêng ứng với PC2 [-0.37741762 -0.92329566 -0.02449161 -0.06694199]


### So sánh 2 thuật toán LDA và PCA:
#### - Thuật toán LDA:
- Là thuật toán thuộc dạng Supervised Learning.
- Quan tâm đến các trục tối đa hóa sự tách biệt giữa nhiều lớp

#### - Thuật toán PCA:
- Là thuật toán thuộc dạng Unsupervised Learning.
- Tìm các trục thành phần tối đa hóa phương sai của dữ liệu.

$⇒$ Từ các kết quả trên, có thể thấy LDA giúp phân cụm chính xác hơn so với PCA nhờ có các labels.
