In [1]:
import numpy as np
import pandas as pd

In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
dataset = pd.read_csv(url, names=names)

In [3]:
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [7]:
X = dataset.drop('Class', 1)
y = dataset['Class']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.


In [10]:
X

sepal-length  sepal-width  petal-length  petal-width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [8]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Class, Length: 150, dtype: object

In [9]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [11]:
X_train

sepal-length  sepal-width  petal-length  petal-width
137           6.4          3.1           5.5          1.8
84            5.4          3.0           4.5          1.5
27            5.2          3.5           1.5          0.2
127           6.1          3.0           4.9          1.8
132           6.4          2.8           5.6          2.2
..            ...          ...           ...          ...
9             4.9          3.1           1.5          0.1
103           6.3          2.9           5.6          1.8
67            5.8          2.7           4.1          1.0
117           7.7          3.8           6.7          2.2
47            4.6          3.2           1.4          0.2

[120 rows x 4 columns]

In [12]:
X_test

sepal-length  sepal-width  petal-length  petal-width
114           5.8          2.8           5.1          2.4
62            6.0          2.2           4.0          1.0
33            5.5          4.2           1.4          0.2
107           7.3          2.9           6.3          1.8
7             5.0          3.4           1.5          0.2
100           6.3          3.3           6.0          2.5
40            5.0          3.5           1.3          0.3
86            6.7          3.1           4.7          1.5
76            6.8          2.8           4.8          1.4
71            6.1          2.8           4.0          1.3
134           6.1          2.6           5.6          1.4
51            6.4          3.2           4.5          1.5
73            6.1          2.8           4.7          1.2
54            6.5          2.8           4.6          1.5
63            6.1          2.9           4.7          1.4
37            4.9          3.1           1.5          0.1
78            6.0          2.9           4.5          1.5
90            5.5          2.6           4.4          1.2
45            4.8          3.0           1.4          0.3
16            5.4          3.9           1.3          0.4
121           5.6          2.8           4.9          2.0
66            5.6          3.0           4.5          1.5
24            4.8          3.4           1.9          0.2
8             4.4          2.9           1.4          0.2
126           6.2          2.8           4.8          1.8
22            4.6          3.6           1.0          0.2
44            5.1          3.8           1.9          0.4
97            6.2          2.9           4.3          1.3
93            5.0          2.3           3.3          1.0
26            5.0          3.4           1.6          0.4

In [13]:
y_train

137     Iris-virginica
84     Iris-versicolor
27         Iris-setosa
127     Iris-virginica
132     Iris-virginica
            ...       
9          Iris-setosa
103     Iris-virginica
67     Iris-versicolor
117     Iris-virginica
47         Iris-setosa
Name: Class, Length: 120, dtype: object

In [14]:
y_test

114     Iris-virginica
62     Iris-versicolor
33         Iris-setosa
107     Iris-virginica
7          Iris-setosa
100     Iris-virginica
40         Iris-setosa
86     Iris-versicolor
76     Iris-versicolor
71     Iris-versicolor
134     Iris-virginica
51     Iris-versicolor
73     Iris-versicolor
54     Iris-versicolor
63     Iris-versicolor
37         Iris-setosa
78     Iris-versicolor
90     Iris-versicolor
45         Iris-setosa
16         Iris-setosa
121     Iris-virginica
66     Iris-versicolor
24         Iris-setosa
8          Iris-setosa
126     Iris-virginica
22         Iris-setosa
44         Iris-setosa
97     Iris-versicolor
93     Iris-versicolor
26         Iris-setosa
Name: Class, dtype: object

In [15]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [16]:
X_train

array([[ 0.61303014,  0.10850105,  0.94751783,  0.73603967],
       [-0.56776627, -0.12400121,  0.38491447,  0.34808318],
       [-0.80392556,  1.03851009, -1.30289562, -1.3330616 ],
       [ 0.25879121, -0.12400121,  0.60995581,  0.73603967],
       [ 0.61303014, -0.58900572,  1.00377816,  1.25331499],
       [-0.80392556, -0.82150798,  0.04735245,  0.21876435],
       [-0.21352735,  1.73601687, -1.19037495, -1.20374277],
       [ 0.14071157, -0.82150798,  0.72247648,  0.47740201],
       [ 0.02263193, -0.12400121,  0.21613346,  0.34808318],
       [-0.09544771, -1.05401024,  0.10361279, -0.03987331],
       [ 1.0853487 , -0.12400121,  0.94751783,  1.12399616],
       [-1.39432376,  0.34100331, -1.41541629, -1.3330616 ],
       [ 1.20342834,  0.10850105,  0.72247648,  1.38263382],
       [-1.04008484,  1.03851009, -1.24663528, -0.81578628],
       [-0.56776627,  1.50351461, -1.30289562, -1.3330616 ],
       [-1.04008484, -2.4490238 , -0.1776889 , -0.29851096],
       [ 0.73110978, -0.

In [17]:
from sklearn.decomposition import PCA

pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [18]:
X_train

array([[ 1.27228206e+00,  3.57878727e-01,  1.80336960e-01,
        -2.18683823e-01],
       [ 1.52231770e-01, -2.99835283e-01,  6.57129626e-01,
        -2.49320747e-01],
       [-2.18764183e+00,  6.17154256e-01, -1.80887051e-01,
         3.66971080e-03],
       [ 9.41913396e-01,  1.21810481e-02,  3.29616253e-01,
        -1.23928051e-02],
       [ 1.76227837e+00, -2.71066387e-01,  3.36678920e-01,
         9.29947613e-02],
       [-8.16806401e-02, -1.04319475e+00,  5.24835677e-01,
        -2.98705715e-02],
       [-1.89794863e+00,  1.48464927e+00, -3.40792097e-01,
         5.29711669e-02],
       [ 9.59395493e-01, -6.91087802e-01,  9.92861246e-02,
        -1.91468714e-01],
       [ 3.65661204e-01, -9.13013087e-02,  2.01390351e-01,
         3.40875107e-02],
       [ 2.31845912e-01, -1.01891237e+00, -2.00913311e-01,
        -8.50013948e-03],
       [ 1.79730127e+00,  3.25092688e-01,  1.91532698e-02,
         1.34801794e-01],
       [-2.40350676e+00, -2.44874760e-01,  5.92229980e-02,
      

In [19]:
explained_variance = pca.explained_variance_ratio_

In [20]:
explained_variance

array([0.72226528, 0.23974795, 0.03338117, 0.0046056 ])

In [21]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [22]:
X_train

array([[ 1.27228206e+00],
       [ 1.52231770e-01],
       [-2.18764183e+00],
       [ 9.41913396e-01],
       [ 1.76227837e+00],
       [-8.16806401e-02],
       [-1.89794863e+00],
       [ 9.59395493e-01],
       [ 3.65661204e-01],
       [ 2.31845912e-01],
       [ 1.79730127e+00],
       [-2.40350676e+00],
       [ 1.82199968e+00],
       [-1.98427118e+00],
       [-2.17073306e+00],
       [-2.55598076e-01],
       [ 1.38862320e+00],
       [ 1.93409268e+00],
       [ 1.12243099e+00],
       [ 1.88169499e+00],
       [ 5.43123767e-02],
       [ 2.70365641e+00],
       [ 6.91516012e-01],
       [ 1.30048660e-02],
       [ 1.22853905e+00],
       [ 1.01881714e+00],
       [ 2.57616370e-01],
       [ 1.44310720e+00],
       [ 1.03458720e+00],
       [ 1.43772035e+00],
       [ 3.84673096e-01],
       [-2.18860624e+00],
       [ 1.05608476e+00],
       [ 1.92641524e-01],
       [-1.12363985e-01],
       [ 1.72424265e-01],
       [ 5.48040969e-01],
       [ 1.88178641e+00],
       [-2.2

In [23]:
X_test

array([[ 1.37128269],
       [ 0.42475842],
       [-2.41090531],
       [ 2.20457368],
       [-2.25849397],
       [ 1.78306101],
       [-2.30431534],
       [ 0.97516555],
       [ 1.15841831],
       [ 0.38498071],
       [ 1.09234574],
       [ 0.66832264],
       [ 0.54112432],
       [ 0.97934704],
       [ 0.63483747],
       [-2.23288987],
       [ 0.58056172],
       [ 0.17606513],
       [-2.12654085],
       [-2.19666954],
       [ 0.88546786],
       [ 0.27702729],
       [-2.251877  ],
       [-2.39601679],
       [ 1.07934479],
       [-2.78023741],
       [-2.13280069],
       [ 0.49199447],
       [-0.48313446],
       [-2.07798432]])