In [ ]:
import numpy as np
from scipy.stats import multivariate_normal
Xmat = np. genfromtxt ('clusterdata.csv', delimiter =',')
K = 3
n, D = Xmat.shape
W = np.array ([[1/3 ,1/3 ,1/3]])
M = np.array ([[-2.0, -4,0],[-3 ,1,-1]], dtype=np.float32)
# Note that if above *all* entries were written as integers , M would
# be defined to be of integer type , which will give the wrong answer
C = np.zeros ((3 ,2 ,2))
C[: ,0 ,0] = 1
C[: ,1 ,1] = 1
p = np.zeros ((3 ,300))
for i in range(0 ,100):
#E-step 
  for k in range(0,K):
    mvn = multivariate_normal ( M[:,k].T, C[k,: ,:] )
    p[k ,:] = W[0,k]* mvn.pdf(Xmat)
# M-Step
  p = (p/sum(p ,0)) # normalize
  W = np.mean(p ,1).reshape (1 ,3)
  for k in range(0,K):
      M[:,k] = (Xmat.T @ p[k ,:].T)/sum(p[k ,:])
      xm = Xmat.T - M[:,k]. reshape (2 ,1)
      C[k,: ,:] = xm @ (xm*p[k ,:]).T/sum(p[k ,:])
print(C)

[[[ 1.74763402  0.03378977]
  [ 0.03378977  0.09495477]]

 [[ 1.37270041  0.91725911]
  [ 0.91725911  1.02833703]]

 [[ 1.92708457 -1.19656403]
  [-1.19656403  1.4378827 ]]]
